# Generated by Django 5.1.2 on 2025-01-28 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='улица')),
                ('house', models.PositiveIntegerField(blank=True, null=True, verbose_name='номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='LevelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.contact', verbose_name='контакты')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='модель')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('levelelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network.levelelement')),
            ],
            bases=('network.levelelement',),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('levelelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network.levelelement')),
            ],
            bases=('network.levelelement',),
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('levelelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network.levelelement')),
            ],
            bases=('network.levelelement',),
        ),
        migrations.AddField(
            model_name='levelelement',
            name='product',
            field=models.ManyToManyField(related_name='products', to='network.product', verbose_name='продукт'),
        ),
    ]
