# Generated by Django 5.1.2 on 2025-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelelement',
            name='credit',
            field=models.FloatField(blank=True, null=True, verbose_name='задолжность'),
        ),
    ]
